### ISSUE TITLE
something missing ?

### ISSUE THREAD

**Issue by evert-hoos** [mikethemadkiwi/busdrivermike#1]
Hi! PolyZone / yarn  is loaded however i cannot start the busdriver script 

Error loading script server.lua in resource busdrivermike-main: @busdrivermike-main/server.lua:3: bad argument #1 to 'decode' (string expected, got nil)
stack traceback:
        [C]: in function 'json.decode'
        @busdrivermike-main/server.lua:3: in main chunk

**Comment by mikethemadkiwi** [comment]
update your server version.
make sure the version of lua you have installed is lua 5.4 if it isnt.
ensure the file bddb,json exists. even if it's empty. 
this is related to the JSON file read. and is only a bug in old cfx server code.
it shouldnt happen with the latest versions.

**Comment by evert-hoos** [comment]
that did the trick thanks! , lovely resource btw :)
