### ISSUE TITLE
Bus is locked

### ISSUE THREAD

**Issue by DjSpyce** [mikethemadkiwi/busdrivermike#3]
![code](https://user-images.githubusercontent.com/108833622/180975982-fb841b30-f3b9-4fb0-85bc-68c704ca60e5.PNG)

When the bus spawns I cant get in it still i even tried lockpicking and it wont let me. Any help would be appreciated.

**Comment by mikethemadkiwi** [comment]
as lockpicking isnt part of this mod, i assume you are using qbcore or esx.
if you ARE, remove buses from the lockpick/vehicle blacklist in that framework.
as this mod is not intended for these frameworks.

**Comment by DjSpyce** [comment]
So I can’t use the mod for qbcore?

**Comment by sondercityrp** [comment]
Yes just make the bus class 17 the blacklisted class in your qb-vechiclekeys folder

**Comment by mikethemadkiwi** [comment]
Yes, you totally can use it with qbcore, it's just not DESIGNED for it without a minor alteration as sonder shows there.
Thanks sonder!

**Comment by DjSpyce** [comment]
Thank you much appreciated I’ll try that.
