### ISSUE TITLE
Bus Arriving Locked

### ISSUE THREAD

**Issue by QU33NSCREATION** [mikethemadkiwi/busdrivermike#5]
I've missed the bus a few times, it seems. When I call the bus, it shows up with doors locked. I'm new to scripting, but have some basic knowledge. Is it possible that you can do a tutorial on how to setup busdrivemike and ways to fix common issues? I looked for the vehicle whitelist, but I'm not even sure I was looking in the right place. Please help. I really like this script.

**Comment by mikethemadkiwi** [comment]
sadly this isnt a problem with my script. the issue is that of the qbcore or esx lockpicking script. depending on your framework.
the ONLY way i know to stop the issue you are having is to add the ```bus, coach & pbus``` models to the exemption list in the lockpick scripts.

**Comment by mikethemadkiwi** [comment]
without doing a dig about... it's likely THIS script that is handling car keys/lockpicking.
[https://github.com/qbcore-framework/qb-vehiclekeys](https://github.com/qbcore-framework/qb-vehiclekeys)
i'd suggest adding the buses into whatever "don't run on this model" or "ignore car" list in in that.
sadly, i dont really do much work in either esx or qbcore, so it's just my best guess at where to find it.
i'd hit the forums if you can't get it to work still. i work a 60 hour week and sadly don't have the time to make instructionals.
